# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
